Add details about datasets with restricted access
mila-iqia/mila-docs pull request #126
Opened 2022-07-18 17:10 UTC by satyaog

2022-07-18 17:11 UTC, satyaog commented
https://mila-docs-staging--126.org.readthedocs.build/en/126/Information.html#datasets

2022-07-18 17:41 UTC, priscillaben reviewed
@satyaog , il doit également y avoir une approbation du "responsable" du groupe/dataset (en général, c'est le prof en charge du projet)

2022-07-18 18:38 UTC, satyaog commented on docs/Information_storage.rst
> +<https://cli-cheatsheet.readthedocs.io/en/latest/#ls>`_.
```suggestion
<https://forms.gle/vDVwD2rZBmYHENgZA>`_.

Datasets in ``datasets/restricted`` are restricted and require an explicite
request to gain access. Please `submit a support ticket
<https://milaquebec.freshdesk.com/a/tickets/new>`_ mentionning the dataset's
access group (ex.: ``scannet_users``), your cluster's username and the
approbation of a member of the group. You can find the dataset's access group
by listing the content of ``/network/datasets/restricted`` with the `ls command
<https://cli-cheatsheet.readthedocs.io/en/latest/#ls>`_.
```

2022-07-21 14:25 UTC, btravouillon requested changes
By default, I would request authorization from the group owner only, not group members.

2022-07-21 14:25 UTC, btravouillon commented on docs/Information_storage.rst
> +a support ticket <https://milaquebec.freshdesk.com/a/tickets/new>`_ mentionning
```suggestion
are restricted and require an explicit request to gain access. Please `submit
a support ticket <https://milaquebec.freshdesk.com/a/tickets/new>`_ mentioning
```

2022-07-25 17:34 UTC, satyaog commented on docs/Information_storage.rst
> +<https://cli-cheatsheet.readthedocs.io/en/latest/#ls>`_.
```suggestion
<https://forms.gle/vDVwD2rZBmYHENgZA>`_.

Datasets in ``datasets/restricted`` are restricted and require an explicit
request to gain access. Please `submit a support ticket
<https://milaquebec.freshdesk.com/a/tickets/new>`_ mentioning the dataset's
access group (ex.: ``scannet_users``), your cluster's username and the
approbation of the group owner. You can find the dataset's access group by
listing the content of ``/network/datasets/restricted`` with the `ls command
<https://cli-cheatsheet.readthedocs.io/en/latest/#ls>`_.
```

2022-07-25 18:38 UTC, btravouillon approved these changes
Looks good to me. 👍

2022-07-27 17:42 UTC, merged