Remind users to acknowledge CC
mila-iqia/mila-docs pull request #131
Opened 2022-10-04 20:53 UTC by breuleux

* Update the Compute Canada link to point to the new website (Alliance Canada).
* Point users to the "Acknowledging the Alliance" page and remind them they should do so for their papers (this can help us with our allocation requests).

I inserted the reminder at the beginning because it sounded natural there, but there may be better spots to place it.

2022-10-04 21:01 UTC, btravouillon requested changes

2022-10-04 21:13 UTC, breuleux commented on docs/Extra_compute_cc.rst
>  clusters provided by the `Compute Canada organisation
Should we change it everywhere else in the file?

2022-10-04 21:13 UTC, btravouillon commented on docs/Extra_compute_cc.rst
>  clusters provided by the `Compute Canada organisation
Nice catch. I guess yes!

2022-10-05 19:06 UTC, btravouillon commented on docs/Extra_compute_cc.rst
>  clusters provided by the `Compute Canada organisation
I opened https://github.com/mila-iqia/mila-docs/issues/132 to handle this in another PR.

2022-10-06 02:13 UTC, btravouillon approved these changes
Looks good to me. 👍

The CC -> DRAC replacement will be handled in a separate PR.

2022-10-06 20:32 UTC, satyaog approved these changes

2022-10-06 20:32 UTC, merged