Add section for account renewal
mila-iqia/mila-docs pull request #207
Opened 2023-07-20 14:27 UTC by gandatchabana

Links to DRAC FAQ and support emails

resolve: #179

2023-07-25 19:16 UTC, satyaog approved these changes

2023-07-25 19:16 UTC, satyaog commented on docs/Extra_compute_drac.rst
> +or the general support team at ``support@tech.alliancecan.ca``.
80 chars line width

```suggestion
All user accounts (Sponsor & Sponsored) have to be renewed annually in order to
keep up-to-date information on active accounts and to deactivate unusued
accounts.

To find out how to renew your account or for any other questions regarding
DRAC's accounts renewal, please head over to their `FAQ
<https://alliancecan.ca/en/services/advanced-research-computing/account-management/account-renewals/account-renewals-faq>`_.

If the FAQ is of no help, you can contact DRAC renewal support team at
``renewals@tech.alliancecan.ca`` or the general support team at
``support@tech.alliancecan.ca``.
```

2023-08-23 20:52 UTC, btravouillon requested changes

2023-08-23 20:52 UTC, btravouillon commented on docs/Extra_compute_drac.rst
> +keep up-to-date information on active accounts and to deactivate unusued
```suggestion
keep up-to-date information on active accounts and to deactivate unused
```

2023-08-23 20:52 UTC, btravouillon commented on docs/Extra_compute_drac.rst
> +To find out how to renew your account or for any other questions regarding
```suggestion
To find out how to renew your account or for any other question regarding
```

2023-09-06 18:04 UTC, satyaog commented
@gandatchabana would you have some time to update this PR?

2023-09-20 17:34 UTC, merged