Add some documentation for podman
mila-iqia/mila-docs pull request #262
Opened 2024-12-03 19:11 UTC by abergeron

This is a draft for the podman docs.

I still need to test the GPU part to make sure it all works as expected.

I would welcome comments about missing sections or details that are not explained.

2024-12-04 14:58 UTC, satyaog commented on docs/Userguide_containers.rst
> +    https://docs.podman.io/en/stable/
```suggestion
.. note::
    Complete Podman Documentation: https://docs.podman.io/en/stable/
```

2024-12-04 14:58 UTC, satyaog commented on docs/Userguide_containers.rst
> +You can use multiple containers in a single job, but you have to be careful about the memory and CPU limits of the job.
```suggestion
You can use multiple containers in a single job, but you have to be careful
about the memory and CPU limits of the job.
```

2024-12-04 14:58 UTC, satyaog commented on docs/Userguide_containers.rst
> +To use a GPU you need to a GPU job and then use the ``--device nvidia.com/gpu=all`` for all GPUs allocated to the job or ``--device nvidia.com/gpu=n`` where n is the gpu you want in the container, st
```suggestion
To use a GPU in a container, you need to a GPU job and then use ``--device
nvidia.com/gpu=all`` to make all GPUs allocated available in the container or
``--device nvidia.com/gpu=N`` where `N` is the gpu index you want in the
container, starting at 0.
```

2024-12-04 14:58 UTC, satyaog commented on docs/Userguide_containers.rst
> +Docker containers are now available on the local cluster without root priviledges using `podman <https://podman.io>`_.
```suggestion
Docker containers are now available on the local cluster without root
priviledges using `podman <https://podman.io>`_.
```

2024-12-04 14:58 UTC, satyaog commented on docs/Userguide_containers.rst
> +Generally any command-line argument accepted by docker will work with podman. this means that you can mostly use docker examples in you find on the web by replacing docker with podman in the command
```suggestion
Generally any command-line argument accepted by docker will work with podman.
This means that you can mostly use the docker examples you find on the web by
replacing `docker` with `podman` in the command line.
```

2024-12-04 14:58 UTC, satyaog commented on docs/Userguide_containers.rst
> +To use podman you can just use the podman command in either a batch script or an interactive job.
```suggestion
To use podman you can just use the `podman` command in either a batch script or
an interactive job.
```

2024-12-04 14:58 UTC, satyaog commented on docs/Userguide_containers.rst
> +One difference in configuration is that for certain technical reasons all the storage for podman (images, containers, ...) is on a job-specific location and will be lost after the job is complete or
```suggestion
One difference in configuration is that for certain technical reasons all the
storage for podman (images, containers, ...) is on a job-specific location and
will be lost after the job is complete or preempted. If you have data that must
be preseved across jobs, you can `mount
<https://docs.podman.io/en/v5.2.4/markdown/podman-run.1.html#mount-type-type-type-specific-option>`_
a local folder inside the container, such as `$SCRATCH` or your home to save
data.
```

2024-12-13 18:53 UTC, btravouillon requested changes

2024-12-13 18:53 UTC, btravouillon commented on docs/Userguide_containers.rst
> +priviledges using `podman <https://podman.io>`_.
```suggestion
Podman containers are now available as tech preview on the Mila cluster
without root privileges using `podman <https://podman.io>`_.
```

2024-12-13 18:53 UTC, btravouillon commented on docs/Userguide_containers.rst
> +To use a GPU in a container, you need to a GPU job and then use ``--device
You need to "queue" a GPU job ?

2024-12-13 19:28 UTC, btravouillon approved these changes
Looks good to me. 👍

2024-12-13 20:08 UTC, obilaniu approved these changes

2024-12-13 20:10 UTC, merged