Add infos about Onboarding and Cluster access policies
mila-iqia/mila-docs pull request #95
Opened 2021-12-02 16:38 UTC by gandarioult

Rajout du lien vers le IT Onboarding Guide + Politique d'accès au Cluster (Core + Staff)

2021-12-02 16:38 UTC, btravouillon commented
Can you wrap the linea to 80 columns ?

2021-12-03 22:01 UTC, satyaog requested changes

2021-12-03 22:01 UTC, satyaog commented on docs/Userguide_login.rst
> +
Best to keep the same number of empty line between paragraph for consistency (so 2 instead of 3 in this case)

2021-12-03 22:05 UTC, satyaog commented
Thanks @gandarioult for your PR! If this is related to #71, you should add the following to the description of this PR:

```

resolves #71
```

This will make GitHub close issue #71 when this PR will be merged.

2021-12-03 22:45 UTC, gandarioult commented
Added 'resolves #71' to the description + committed all suggestions

2021-12-03 22:56 UTC, satyaog approved these changes

2021-12-03 22:56 UTC, satyaog commented on docs/Userguide_login.rst
>  SSH Login
Hehe there's still 3 new lines here but that's minor an I approve this PR

```suggestion
Core Professors - Staff**


SSH Login
```

2021-12-16 14:30 UTC, achillemyette1 approved these changes

2021-12-16 18:10 UTC, btravouillon commented
@fosterrath-mila un avis avant merge ?

2021-12-20 14:21 UTC, merged